
#include "main.h"

SEGMENT_T seg_one = {
    .SEGMENT_PINS[0].PORT = PORTC_INDEX,
    .SEGMENT_PINS[0].PIN = PIN0,
    .SEGMENT_PINS[0].LOGIC = GPIO_LOW,
    .SEGMENT_PINS[0].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .SEGMENT_PINS[1].PORT = PORTC_INDEX,
    .SEGMENT_PINS[1].PIN = PIN1,
    .SEGMENT_PINS[1].LOGIC = GPIO_LOW,
    .SEGMENT_PINS[1].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .SEGMENT_PINS[2].PORT = PORTC_INDEX,
    .SEGMENT_PINS[2].PIN = PIN2,
    .SEGMENT_PINS[2].LOGIC = GPIO_LOW,
    .SEGMENT_PINS[2].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .SEGMENT_PINS[3].PORT = PORTC_INDEX,
    .SEGMENT_PINS[3].PIN = PIN3,
    .SEGMENT_PINS[3].LOGIC = GPIO_LOW,
    .SEGMENT_PINS[3].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .SEGMENT_TYPE = SEGMENT_COMMON_ANODE
};
    
uint8 counter = 0;
    
void main(void) {
    STD_RETURN_TYPE RET = E_NOT_OK;
    APPLICATION_INITIALIZE();
    while(1) {
        for(counter = 0; counter <= 9; counter++) {
            RET = SEVEN_SEGMENT_WRITE_NUMBER(&seg_one, counter);
            __delay_ms(375);
        }
    }
    
    return;
}

void APPLICATION_INITIALIZE(void) {
    STD_RETURN_TYPE RET = E_NOT_OK;
    SEVEN_SEGMENT_INITIALIZE(&seg_one);
}