
#ifndef CCP_CFG_H
#define	CCP_CFG_H

#define CCP_CFG_CAPTURE_MODE_SELECTED  0x00
#define CCP_CFG_COMPARE_MODE_SELECTED  0x01
#define CCP_CFG_PWM_MODE_SELECTED      0x02

#define CCP1_CFG_SELECTED_MODE (CCP_CFG_CAPTURE_MODE_SELECTED)
#define CCP2_CFG_SELECTED_MODE (CCP_CFG_COMPARE_MODE_SELECTED)


#endif	/* CCP1_CFG_H */
