
#ifndef STD_LIBRARIES_H
#define	STD_LIBRARIES_H


/* SECTION : INCLUDES */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* SECTION : MACRO DECLARATIONS */
/* SECTION : MACRO FUNCTION DECLARATIONS */
/* SECTION : DATATYPE DECLARATIONS */
/* SECTION : FUNCTION DECLARATIONS */


#endif	/* STD_LIBRARIES_H */

