
#ifndef DEVICE_CONFIG_H
#define	DEVICE_CONFIG_H


/* SECTION : INCLUDES */

/* SECTION : MACRO DECLARATIONS */

/* SECTION : MACRO FUNCTION DECLARATIONS */
/* SECTION : DATATYPE DECLARATIONS */
/* SECTION : FUNCTION DECLARATIONS */

#endif	/* DEVICE_CONFIG_H */

